FROM php:fpm
RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        unzip \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        librabbitmq-dev \
    && docker-php-ext-install \
        pdo_mysql \
        zip \
    && pecl install amqp \
    && docker-php-ext-enable amqp

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
COPY project/ /var/www/project
COPY build/php/wait-for-it.sh /usr/bin/wait-for-it

WORKDIR /var/www/project/

RUN cd /var/www/project && composer install





